Feat/0x5459/pc1 label memory numa aware
ipfs-force-community/rust-fil-proofs pull request #1
Opened 2022-07-04 08:11 UTC by 0x5459

resolve ipfs-force-community/venus-cluster#85

1. Add shm::NumaPool, used to allocate pre-set shared memory.
2. Modify the pc1 phase setup_create_label_memory function. Prefer to get the available memory from the current numa noode, or use anonymous mmap to allocate memory if it is not available.

2022-07-05 01:58 UTC, dtynn requested changes

2022-07-05 01:58 UTC, dtynn commented on storage-proofs-porep/src/stacked/vanilla/cores.rs
> +    numa_node: NumaNodeIndex,
这里是不是用 Option 更好？

2022-07-05 01:58 UTC, dtynn commented on storage-proofs-porep/src/stacked/vanilla/memory_handling.rs
> +        unsafe { NUMA_POOL = Some(NumaPool::new(numa_shm_files)) };
init 需不需要考虑引入 类似 `Once` ？

2022-07-05 01:58 UTC, dtynn commented on storage-proofs-porep/src/stacked/vanilla/memory_handling.rs
> +    static mut NUMA_POOL: Option<NumaPool> = None;
这里的 pool 初始化是交给使用层去做的？
能否考虑类似 parent cache / params 的做法，通过 激活开关 + 默认位置 + 标准的命名方式 搭配，使用 lazy_static 来 **隐式** 地完成初始化？

参考 https://github.com/filecoin-project/rust-fil-proofs/blob/master/storage-proofs-core/src/settings.rs

2022-07-05 02:13 UTC, 0x5459 commented on storage-proofs-porep/src/stacked/vanilla/memory_handling.rs
> +    static mut NUMA_POOL: Option<NumaPool> = None;
这样做是考虑不想把命名规则耦合到这里来

2022-07-05 02:31 UTC, dtynn commented on storage-proofs-porep/src/stacked/vanilla/memory_handling.rs
> +    static mut NUMA_POOL: Option<NumaPool> = None;
命名规则可以不放在实现一层，但是放在类似 storage-proofs-porep 是没问题的

2022-07-05 02:39 UTC, dtynn commented on storage-proofs-porep/src/stacked/vanilla/memory_handling.rs
> +            Some(shm_mem) => Memory::Shm(shm_mem),
如果不能获取numa node ，考虑直接进行常规分配？

2022-07-05 15:16 UTC, 0x5459 commented on storage-proofs-porep/src/stacked/vanilla/memory_handling.rs
> +    static mut NUMA_POOL: Option<NumaPool> = None;
Resolved

2022-07-05 15:17 UTC, 0x5459 commented on storage-proofs-porep/src/stacked/vanilla/memory_handling.rs
> +            Some(shm_mem) => Memory::Shm(shm_mem),
allocate_layer() 和 NumaPoll::acquire() 的第二个参数 `numa_node ` 均已被移除。 使用 numa::current_numa_node() 代替

2022-07-06 05:21 UTC, dtynn approved these changes
LGTM

2022-07-06 05:23 UTC, merged